### ISSUE TITLE
Glance plugin update site is not available

### ISSUE THREAD

**Issue by informatik01** [ystrot/glance#34]
The official Glance update site for Eclipse **http://eclipse-glance.googlecode.com/svn/site/** is not available (down ?):

![untitled](https://cloud.githubusercontent.com/assets/11339880/15285697/8f2e7b4e-1b61-11e6-9eec-26bfbb51b92b.png)

So currently you **can't install Glance plugin** (both thru Eclipse Marketplace and by dragging and dropping the "Install" button).

**Comment by ujhelyiz** [comment]
This is related to the shutdown of Google Code; nothing hosted there is available anymore. I was going to create an unofficial site for the plug-in as I use it very often, but had no time to do it yet.

**Comment by informatik01** [comment]
OK, I see. Thanks for the clarification.

**Comment by ujhelyiz** [comment]
I have created an unofficial update site on bintray: https://dl.bintray.com/ujhelyiz/generic/glance/1.1.2/repository/

I had to modify the build scripts meanwhile, and had to rename the features, so it will not update correctly, but it works in my experience. If I will have time, it is possible I will do other work with this plug-in, but no promises in this regard. All required changes are available from my fork of the repository: https://github.com/ujhelyiz/glance

**Comment by informatik01** [comment]
Thank you for your efforts!

**Comment by szotsaki** [comment]
@ujhelyiz Could you please look at the two (same) linked issues? Sometimes Eclipse cannot initialise a new Editor at all with Glance backtrace lines being on the top.

Thank you!

**Comment by ujhelyiz** [comment]
I'll try to have a look at them, but I have my hands a little bit full at the moment.

**Comment by szotsaki** [comment]
Thank you! It's really easy to reproduce them. Just select a word in the editor, press `Ctrl+Alt+F` then
- open a new editor in Project Explorer and
- click into Project Explorer and start typing.

Both result in some kind of exception.

**Comment by ystrot** [comment]
There is another fork with Neon support: https://github.com/cypher256/glance. You can use following update site to install it: https://raw.githubusercontent.com/cypher256/glance/master/releng/com.xored.glance-updatesite/site.xml

We're planning to collect all useful fixes and move back official update site in the nearest time.

**Comment by tk303** [comment]
Thank you. I love your little tool. It's very helpful.

**Comment by ystrot** [comment]
The new official update site is http://www.exyte.com/glance/updates

**Comment by ujhelyiz** [comment]
Thanks for the new site. However, I have a question: is there any specific reason the new update site contains version 1.0.0 of Glance, while the most recent release had version 1.1.0 (or maybe 1.1.1)?

**Comment by ystrot** [comment]
Looks like it was done by mistake, I'll update it shortly.

**Comment by ystrot** [comment]
The latest version now is 1.2.0
