### ISSUE TITLE
Not working correctly when installed on Neon 4.6.0M7 64-bit 

### ISSUE THREAD

**Issue by RochesterMark** [ystrot/glance#35]
I see very strange behavior in the project explorer window when installed on a 64 bit version of eclipse. I'm currently running the version below but have seen this on previous Mars and Neon releases. It would be great to get his fixed as It's one of my favorite additions to eclipse.

Eclipse for Parallel Application Developers
Version: Neon Milestone 7 (4.6.0M7)
Build id: 20160505-1310

**Comment by szotsaki** [comment]
Seems to be fixed in a fork. See here: https://github.com/ystrot/glance/issues/34#issuecomment-221998394

**Comment by asalnik** [comment]
Fixed in 1.2.1.
