### ISSUE TITLE
Diverging Eclipse and Github code, Bug 520450

### ISSUE THREAD

**Issue by jmiserez** [ystrot/glance#44]
Hi,

I installed Glance (1.2.1.201702271753 com.xored.glance.feature.group, xored software, Inc.) from the Eclipse Marketplace (https://marketplace.eclipse.org/content/glance).

I'm experiencing [Bug 520413](https://bugs.eclipse.org/bugs/show_bug.cgi?id=520413#attach_269626) / [Bug 520450](https://bugs.eclipse.org/bugs/show_bug.cgi?id=520450), which seems to have been fixed with this Gerrit change: https://git.eclipse.org/r/#/c/102880/

But the change doesn't seem to be merged into the Plugin on the marketplace or the code in this Github repo. Is there a Glance version/build with all the latest fixes?

The version available from e4 is "Eclipse Glance - Incremental text search 0.0.1.v20171117-1039", which looks older from the version number.

**Comment by ystrot** [comment]
Hi Jeremie,

Glance is not supported on the github anymore, so please uninstall your current version and use the version from e4. New plugins have different identifiers and lower qualifiers because it's in incubator yet. However this is a superior version.

**Comment by jmiserez** [comment]
Thanks, that fixes the bug. I now have 0.0.1.v20171117-1039 from http://download.eclipse.org/e4/snapshots/org.eclipse.e4.ui

I had to manually delete the old files under 
plugins/com.xored.glance.ui.controls_1.2.1.201702271753.jar
plugins/com.xored.glance.ui.viewers_1.2.1.201702271753.jar
plugins/com.xored.glance.ui_1.2.1.201702271753.jar

though, as the Preferences tree had 2 Glance entries for some reason, even though I uninstalled 1.2.1 before installing the new one.
